### ISSUE TITLE
API: (GET) Get the list of products

### ISSUE THREAD

**Issue by gonzalesedwin1123** [OpenSPP/openspp-api#10]
Reference: API doc: https://docs.google.com/document/d/1jGVTC4WLons2elJ0RprPSRrN38d_LR84E3kRmnCX6iI/edit#heading=h.e7huwoo61keb

Repository: https://github.com/OpenSPP/openspp-api

- [x] Added a new API for getting the list of products

Output Fields:

- id
- name
- product_category_id
- unit_of_measure_id
- img
- last_updated

API: /api/spp_api/1/Products

**Comment by adriancris** [comment]
@emjay0921 API should not return all the fields specially the product image as per @gonzalesedwin1123 
Changing the status to In Progress

**Comment by emjay0921** [comment]
I only retained the id and name field.

**Comment by adriancris** [comment]
QA Passed
Working as expected.
![image](https://github.com/OpenSPP/openspp-api/assets/138551361/98cba94a-704f-4629-a203-84e560b80461)

**Comment by adriancris** [comment]
tested and approved without comments
