### ISSUE TITLE
API: (GET) Get the list of product groups

### ISSUE THREAD

**Issue by gonzalesedwin1123** [OpenSPP/openspp-api#11]
- Product Groups =Product Categories

Reference: API doc: https://docs.google.com/document/d/1jGVTC4WLons2elJ0RprPSRrN38d_LR84E3kRmnCX6iI/edit#heading=h.zbulsrnegb9m

Repository: https://github.com/OpenSPP/openspp-api

**Comment by adriancris** [comment]
Setting back to In Progress.
Waiting for "last_updated" to reflect in the API.

**Comment by nhatnm0612** [comment]
> 
> Setting back to In Progress.
> Waiting for "last_updated" to reflect in the API.

@adriancris should be good after redeploying

**Comment by adriancris** [comment]
QA Passed.
Working as expected.


![Image](https://github.com/OpenSPP/openspp-api/assets/138551361/bd6c93a0-112d-4453-aa4a-fea33149021b)

**Comment by adriancris** [comment]
tested and approved without comments
