### ISSUE TITLE
API: (GET) Get the list of currencies

### ISSUE THREAD

**Issue by gonzalesedwin1123** [OpenSPP/openspp-api#12]
Reference: API doc: https://docs.google.com/document/d/1jGVTC4WLons2elJ0RprPSRrN38d_LR84E3kRmnCX6iI/edit#heading=h.rp84oews93a7

Repository: https://github.com/OpenSPP/openspp-api

**How to use:**

GET list of currencies

Full Path: /api/spp+api/1/res.currency/
Method: GET
Sample payload
- {
    "request_id": "gh8aus9"
}

Sample Response
- {
    "results": [
        {
            "id": 1,
            "decimal_places": 2,
            "full_name": "Euro",
            "name": "EUR",
            "write_date": "2023-06-27 02:36:15"
        },
        {
            "id": 2,
            "decimal_places": 2,
            "full_name": "United States dollar",
            "name": "USD",
            "write_date": "2023-06-27 02:38:45"
        }
    ],
    "total": 2,
    "offset": 0,
    "limit": 500,
    "version": 1,
    "time_stamp": "2023-08-07 05:17:58.819248",
    "reply_id": "9a54e2eb-b17f-423a-adc6-cd7d89b049c9"
}

GET details of specific currency

Full Path: /api/spp+api/1/res.currency/<currency_id:int>
Method: GET
Sample payload
- {
    "request_id": "gh8aus92"
}

Sample Response
- {
    "id": 1,
    "decimal_places": 2,
    "full_name": "Euro",
    "name": "EUR",
    "write_date": "2023-06-27 02:36:15",
    "time_stamp": "2023-08-07 05:21:01.088966",
    "reply_id": "67e28d4f-f6eb-442e-8ef4-c01f1bf3af34"
}

**Comment by adriancris** [comment]
QA Passed
Working as expected


![Image](https://github.com/OpenSPP/openspp-api/assets/138551361/7641b1c8-b4c2-4fb5-ab12-6d049d1ca892)

**Comment by adriancris** [comment]
tested and approved without comments
