### ISSUE TITLE
API: (GET) Get the list of service point users

### ISSUE THREAD

**Issue by gonzalesedwin1123** [OpenSPP/openspp-api#13]
Dependencies:
- [Associate a company and contacts to each service point.](https://github.com/OpenSPP/openspp-registry/issues/245)

Reference: API doc: https://docs.google.com/document/d/1jGVTC4WLons2elJ0RprPSRrN38d_LR84E3kRmnCX6iI/edit#heading=h.vfsxkidn231n

Repository: https://github.com/OpenSPP/openspp-api

**How to Use:**

GET list of service point users

Full Path: /api/spp+api/1/service_point_users/
Method: GET
Sample Payload
- {
    "request_id": "g86s1"
}

Sample Response
- {
    "results": [
        {
            "id": 128,
            "active": true,
            "login": "red@smail.com",
            "name": "testuser2",
            "service_point_ids": [
                738,
                737
            ],
            "write_date": "2023-09-11 08:57:38"
        }
    ],
    "total": 1,
    "offset": 0,
    "limit": 500,
    "version": 1,
    "time_stamp": "2023-09-11 09:00:28.515214",
    "reply_id": "ed7e885e-0fbf-4e07-8d62-0fd67f2dc99a"
}

GET details of specific service point user

Full Path: /api/spp+api/1/service_point_users/<user_id:int>
Method: GET
Sample Payload
- {
    "request_id": "g86s12"
}

Sample Response
- {
    "id": 128,
    "active": true,
    "login": "red@smail.com",
    "name": "testuser2",
    "service_point_ids": [
        738,
        737
    ],
    "write_date": "2023-09-11 08:57:38",
    "time_stamp": "2023-09-11 09:01:18.968209",
    "reply_id": "5911b8b0-511e-4dec-bacd-c4e0a48a452d"
}

**Comment by adriancris** [comment]
BUG: API is not updated when a contact/user is removed from the company

**Comment by adriancris** [comment]
BUG: Only contacts/users who are newly assigned with a company are added as service point users. Contacts/users who were already assigned with a company are not added as service point users.

**Comment by adriancris** [comment]
The fix for the bugs above will also affect this ticket: Associate a company and contacts to each service point.#245

**Comment by adriancris** [comment]
@reichie020212 
1. Password is still showing in the API
2. When an individual's company is removed in Contacts, API still gets that user.

**Comment by reichie020212** [comment]
@gonzalesedwin1123 I added a new PR

**Comment by adriancris** [comment]
@reichie020212 
A service point user still shows up in the API even when the company associated to it has already been deleted.

**Comment by jeremi** [comment]
same as https://github.com/OpenSPP/openspp-registry/issues/245

**Comment by adriancris** [comment]
QA Passed.
Working as expected.
Test cases executed: TSOS-119
