### ISSUE TITLE
API: (GET) Vouchers

### ISSUE THREAD

**Issue by gonzalesedwin1123** [OpenSPP/openspp-api#14]
Reference: API doc: https://docs.google.com/document/d/1jGVTC4WLons2elJ0RprPSRrN38d_LR84E3kRmnCX6iI/edit#heading=h.rgxegi121ocw

Repository: https://github.com/OpenSPP/openspp-api

**Comment by adriancris** [comment]
Setting the status back to in progress as @emjay0921 is updating this ticket
update is about entitlement_id

**Comment by emjay0921** [comment]
Added another API for inkind vouchers.

**Comment by dasunhegoda** [comment]
add the `card_number` & `voucher_number`

**Comment by emjay0921** [comment]
New PR Linked for adding the card_number and voucher_number.

**Comment by adriancris** [comment]
tested and approved but actions were needed
