### ISSUE TITLE
API: (POST) Transactions

### ISSUE THREAD

**Issue by gonzalesedwin1123** [OpenSPP/openspp-api#15]
Dependencies:
- [Add models to record transaction events#84](https://github.com/OpenSPP/openspp-program/issues/84)

Reference: API doc: https://docs.google.com/document/d/1jGVTC4WLons2elJ0RprPSRrN38d_LR84E3kRmnCX6iI/edit#heading=h.hrz15yyupge3

Repository: https://github.com/OpenSPP/openspp-api

**Comment by gonzalesedwin1123** [comment]
@dasunhegoda I think we need to have a separate API for In-kind entitlement transactions. We have a different model for cash and in-kind entitlements.

**Comment by dasunhegoda** [comment]
@gonzalesedwin1123 Let's proceed with two APIs.

**Comment by adriancris** [comment]
QA Passed
Working as expected

TSOS-121
TSOS-122

**Comment by adriancris** [comment]
hi @gonzalesedwin1123 
timestamp_transaction_created parameter is not correctly displayed. It is automatically set to UTC+00:00 this happens only in Famoco instance. Setting this back to in progress

**Comment by dasunhegoda** [comment]
We need to add `reciept_no` upon the request of Famoco.

**Comment by dasunhegoda** [comment]
@emjay0921 : Could you pls work on the above?

cc: @gonzalesedwin1123

**Comment by emjay0921** [comment]
Okay

**Comment by emjay0921** [comment]
Added the PR for adding the receipt_no to transactions.

Also this PR is also needed: https://github.com/OpenSPP/openspp-program/pull/116

**Comment by adriancris** [comment]
@gonzalesedwin1123 
setting back to in progress as timestamp_transaction_created parameter has not yet been cleared.

**Comment by adriancris** [comment]
timestamp_transaction_created parameter should be written in UTC
QA Passed
