### ISSUE TITLE
API: (GET) Get the list of countries

### ISSUE THREAD

**Issue by gonzalesedwin1123** [OpenSPP/openspp-api#16]
Reference: API doc: https://docs.google.com/document/d/1jGVTC4WLons2elJ0RprPSRrN38d_LR84E3kRmnCX6iI/edit#heading=h.32gw59j9fhxs

Repository: https://github.com/OpenSPP/openspp-api

**Comment by gonzalesedwin1123** [comment]
.

**Comment by dasunhegoda** [comment]
It's just the countries and country offices are list in the API 11(Get the list of the companies)

**Comment by adriancris** [comment]
hi @nhatnm0612 

kindly check this side-by-side comparison between the documentation and the actual result in postman for Get the list of countries 

https://drive.google.com/file/d/1tsEidd6nPZK-7N-WA30F3ejk1dYxA_nY/view?usp=drive_link

**Comment by adriancris** [comment]
QA Passed
Working as expected
![image](https://github.com/OpenSPP/openspp-api/assets/138551361/df351265-294d-4777-856d-909a8b140629)

**Comment by adriancris** [comment]
tested and approved without comments
