### ISSUE TITLE
API: (GET) Get the list of the companies

### ISSUE THREAD

**Issue by gonzalesedwin1123** [OpenSPP/openspp-api#17]
Companies = Country Office

Dependencies:

- [Create a module that allow to create country office (aka company in odoo) and configure it](https://github.com/OpenSPP/newlogic-sp/issues/3)

Reference: API doc: https://docs.google.com/document/d/1jGVTC4WLons2elJ0RprPSRrN38d_LR84E3kRmnCX6iI/edit#heading=h.vwisp81brnh6

Repository: https://github.com/OpenSPP/openspp-api

**How to Use**

GET list of countries

Full Path: /api/spp+api/1/res.company/
Method: GET
Sample Payload
- {
    "request_id": "dg1dz"
}

Sample Response
- {
    "results": [
        {
            "id": 2,
            "name": "My Company (Chicago)"
        },
        {
            "id": 5,
            "name": "dfdfdg"
        },
        {
            "id": 4,
            "name": "qweqwert"
        },
        {
            "id": 3,
            "name": "sadness"
        },
        {
            "id": 6,
            "name": "testing_company1"
        },
        {
            "id": 7,
            "name": "ttttyyy"
        },
        {
            "id": 1,
            "name": "PDS"
        }
    ],
    "total": 7,
    "offset": 0,
    "limit": 500,
    "version": 1,
    "time_stamp": "2023-08-07 06:15:08.141135",
    "reply_id": "aa2a4d5d-37ac-4c75-a6e8-44eb062918a3"
}

GET list of countries

Full Path: /api/spp+api/1/res.company/<company_id:int>
Method: GET
Sample Payload
- {
    "request_id": "dg1dz2"
}

Sample Response
- {
    "id": 2,
    "name": "My Company (Chicago)",
    "time_stamp": "2023-08-07 06:16:47.996276",
    "reply_id": "c69ae5c7-5579-449c-9455-5e249a88f219"
}

**Comment by adriancris** [comment]
QA Passed
Working as expected
![image](https://github.com/OpenSPP/openspp-api/assets/138551361/db91ec34-75fb-4f85-baf3-4d8e0371228e)

**Comment by adriancris** [comment]
tested and approved without comments
