### ISSUE TITLE
API: (POST) Devices

### ISSUE THREAD

**Issue by gonzalesedwin1123** [OpenSPP/openspp-api#18]
Devices = Service Point Terminal Devices

Reference: API doc: https://docs.google.com/document/d/1jGVTC4WLons2elJ0RprPSRrN38d_LR84E3kRmnCX6iI/edit#heading=h.v19ha0dwodd1

Repository: https://github.com/OpenSPP/openspp-api

**Comment by nhatnm0612** [comment]
Service point terminal devices will be a new model for SPP, using these fields to store data sent by Famoco:

- service_point_id: M2o to service point
- android_version: int
- device_model: string
- service_point_terminal_device_id: string - external ID
- status: bool

**Comment by adriancris** [comment]
QA Approve
Working as expected

**Comment by adriancris** [comment]
tested and approved without comments
