### ISSUE TITLE
API: (GET) Get the list of units of measure

### ISSUE THREAD

**Issue by gonzalesedwin1123** [OpenSPP/openspp-api#20]
Reference: API doc: https://docs.google.com/document/d/1jGVTC4WLons2elJ0RprPSRrN38d_LR84E3kRmnCX6iI/edit#heading=h.sy4k1jqu545x

Repository: https://github.com/OpenSPP/openspp-api

**Comment by adriancris** [comment]
hi @nhatnm0612 

kindly check this side-by-side comparison between the documentation and the actual result in postman for Get the list of units of measure

https://drive.google.com/file/d/13oRzyl0DsLUBUiNGLEN1hGgejYsvhrMB/view?usp=drive_link

**Comment by adriancris** [comment]
QA Passed
Working as expected



![Image](https://github.com/OpenSPP/openspp-api/assets/138551361/dba19019-4349-431c-bb1f-9bee5c50faf7)

**Comment by adriancris** [comment]
tested and approved without comments
