### ISSUE TITLE
API: (PUT) Service Point Device

### ISSUE THREAD

**Issue by gonzalesedwin1123** [OpenSPP/openspp-api#34]
Reference: API doc: https://docs.google.com/document/d/1jGVTC4WLons2elJ0RprPSRrN38d_LR84E3kRmnCX6iI/edit#heading=h.k88hp7vejm2y

Repository: https://github.com/OpenSPP/openspp-api

**How to Use:**

FullPath: /api/spp+api/1/ServicePointDevice/<id:int> 
Method: PUT
Sample data
- {
    "request_id": "jh9a6sd",
    "service_point_id": 3,
    "service_point_terminal_device_id": "hs71n",
    "device_model": "z791",
    "android_version": 10,
    "is_active": false
}

Sample Response
- {
    "time_stamp": "2023-08-04 09:54:09.240964",
    "reply_id": "7b980d24-6b8e-4341-9cdd-f71588793883"
}

**Comment by adriancris** [comment]
@reichie020212 updated the code to change the state of is_active using API

**Comment by adriancris** [comment]
QA Passed
Working as expected

**Comment by adriancris** [comment]
tested and approved without comments
