### ISSUE TITLE
XML-RPC API: Beneficiary

### ISSUE THREAD

**Issue by gonzalesedwin1123** [OpenSPP/openspp-api#35]
Reference: API doc: https://docs.google.com/document/d/1jGVTC4WLons2elJ0RprPSRrN38d_LR84E3kRmnCX6iI/edit#heading=h.q0etezwkcw9d

Repository: https://github.com/OpenSPP/openspp-api

We will use XML-RPC for this API instead of implementing it using REST. The limitation of using XML-RPC is that we will have to stick to Odoo's authentication module.

**Comment by emjay0921** [comment]
Preparing a sample client which will be able to use Odoo XML-RPC to be used by the QA.

**Comment by emjay0921** [comment]
Exported Postman sent.

**Comment by adriancris** [comment]
QA Passed
Working as expected

Individual

![Image](https://github.com/OpenSPP/openspp-api/assets/138551361/371ffe5e-d2a7-49af-93b7-1e1a19858959)


*
*
*

Group

![Image](https://github.com/OpenSPP/openspp-api/assets/138551361/05ab969a-fd83-4ed1-8707-e0441d9e19c3)

**Comment by adriancris** [comment]
tested and approved without comments
