### ISSUE TITLE
XML-RPC API: Beneficiary

### ISSUE THREAD

**Issue by gonzalesedwin1123** [OpenSPP/openspp-api#36]
Reference: API doc: https://docs.google.com/document/d/1jGVTC4WLons2elJ0RprPSRrN38d_LR84E3kRmnCX6iI/edit#heading=h.4hinyjcw79by

Repository: https://github.com/OpenSPP/openspp-api

We will use XML-RPC for this API instead of implementing it using REST. The limitation of using XML-RPC is that we will have to stick to Odoo's authentication module.

**Comment by emjay0921** [comment]
Preparing a sample client which will be able to use Odoo XML-RPC to be used by the QA.

**Comment by emjay0921** [comment]
Exported Postman sent.

**Comment by adriancris** [comment]
[BUG] Registrant ID does not retain when updating an individual or group's information

**Comment by jeremi** [comment]
Didn't we said we are not doing any custom API for this?

**Comment by dasunhegoda** [comment]
@jeremi, It's XML-RPC.

**Comment by adriancris** [comment]
QA Passed
Working as expected
Test cases executed:
TSOS-135 to 139
