### ISSUE TITLE
API: (GET) Groups

### ISSUE THREAD

**Issue by dasunhegoda** [OpenSPP/openspp-api#40]
API Doc Reference: https://docs.google.com/document/d/1jGVTC4WLons2elJ0RprPSRrN38d_LR84E3kRmnCX6iI/edit?usp=sharing

**Comment by emjay0921** [comment]
I updated the result @adriancris .

**Comment by adriancris** [comment]
QA Passed
Working as expected



![Image](https://github.com/OpenSPP/openspp-api/assets/138551361/ec2bee49-9dbe-4056-b6bf-d8b1ddfdac9e)

**Comment by adriancris** [comment]
tested and approved without comments
