### ISSUE TITLE
Set the appropriate status of entitlements when the API: (POST) Transactions was executed

### ISSUE THREAD

**Issue by gonzalesedwin1123** [OpenSPP/openspp-api#42]
Auto-set the correct entitlement status depending on the transaction types.

**Comment by emjay0921** [comment]
Hi @dasunhegoda I want to know the different transaction types and their corresponding value in the entitlements status ().

**Comment by dasunhegoda** [comment]
@emjay0921 : Here is the list for now: TOPUP, VOID, EXPIRED, PURCHASE

**Comment by emjay0921** [comment]
Hi @dasunhegoda can we change the Repository of this to openspp-programs?

**Comment by dasunhegoda** [comment]
Hi @emjay0921, Yes sure, I presume, you are referring to the logic to be executed based on the tx state.

**Comment by emjay0921** [comment]
No, the module I'm creating will be in openspp-programs github repository. I can't link this ticket to the PR if it's not set in the right repository.

**Comment by dasunhegoda** [comment]
@emjay0921 will implement manual closing of cycles

**Comment by adriancris** [comment]
@emjay0921 
Expected status for entitlements that are fully redeemed is wrongly displayed
Expected status for entitlements that have not been deducted is wrongly displayed
Updating the status back to dev

**Comment by emjay0921** [comment]
Updated. Setting status to in-review.

**Comment by adriancris** [comment]
QA Passed
Working as expected
Test cases executed:
TSOS-185
TSOS-188

**Comment by adriancris** [comment]
1. For non-cash transactions, the amounts or value_remaining is no longer needed.

2.  value_remaining in cash should also be removed. We can maintain it in the DB for now, We can just remove it in the payload and in the tree views of the UI.

@gonzalesedwin1123
