### ISSUE TITLE
API Improvements v2

### ISSUE THREAD

**Issue by dasunhegoda** [OpenSPP/openspp-api#60]
Famoco proposed the following.

1. last_modified_date for the following entities as o/p param:
- County
- Currency
- Company
- ServicePoint
- ServicePointUser
- ServicePointDevice
- Product
- Unit of Measure

2. The fields unit_of_measure_id and product_category_id are missing for the Product entity.

**Comment by adriancris** [comment]
hi @emjay0921 

1. No last_updated output parameter on the following APIs:

Country
Companies
Service Points
Service Point Devices
Products
Unit of Measure

2. unit_of_measure_id and product_category_id are still missing for the Product entity

**Comment by adriancris** [comment]
QA Passed.
Working as expected.
TCs executed/reference:

TSOS-115 to 116
TSOS-118 to 119
TSOS-123 to 124
TSOS-126 to 127

**Comment by adriancris** [comment]
tested and approved without comments
