### ISSUE TITLE
Enhance API and UI to Filter Service Points by Program

### ISSUE THREAD

**Issue by dasunhegoda** [OpenSPP/openspp-api#64]
API Modification:

- Extend the API to include a filtering mechanism based on program_id.
- When a program_id is provided, the API should solely return the service points associated with the specified program.
- In the absence of a program_id, all service points should be returned.

UI Enhancement:

- ~~Introduce a dropdown menu within the service point UI to enable program selection~~ [by @nhatnm0612 - 2023/11/13]
⬆️ due to `program_id` is in m2m relationship with service point via entitlement, the dropdown UI is not efficiency, user should not select it directly via UI, it should be calculated through each program's cycle entitlement. Instead of this dropdown menu to select, I suggested to do a badge for each program name to show enduser how this service point is having relation with any or all programs

**Comment by adriancris** [comment]
QA Passed.
Working as expected.
Test cases executed: TSOS-115, TSOS-180 to 181

**Comment by adriancris** [comment]
tested and approved without comments
