### ISSUE TITLE
G2P Connect API Implementation - OpenCRVS Integration

### ISSUE THREAD

**Issue by dasunhegoda** [OpenSPP/openspp-api#67]
Website: https://g2pconnect.global
High-Level Requirement: https://docs.google.com/document/d/1AI8YhMSuFxP3MtT9l-oY3OA6__m6bmM65g0Jf0sZm6o/edit?usp=sharing

API spec: https://g2p-connect.github.io/specs/release/html/registry_core_api_v1.0.0.html
https://digital-convergence-initiative-d.gitbook.io/dci-standards-1/dci/readme

- Implement the synchronous approach for the API as per the guidelines and specifications provided.
- Ensure the implementation aligns with the requirements outlined in the documentation provided.
- The implementation needs to comply precisely with the API specifications provided, ensuring accuracy and consistency
- Postman collection to be created
- Currently, the plan is to implement the search in the CR. 

Sample payloads : https://gist.github.com/naftis/a342c2906704a8f71141405c2ce61660

**Comment by nhatnm0612** [comment]
[OpenCRVS Local Installation Guide](https://documentation.opencrvs.org/setup/3.-installation/)

I did use docker version installation, but running failed due to container out of memory error

[OpenCRVS core repo](https://github.com/opencrvs/opencrvs-core)

there is another option [recommended by installation guide above] that is using `setup.sh` bash script, will check later

**Comment by dasunhegoda** [comment]
@reichie020212 : Can you update the ticket with the list of changes you are doing?

**Comment by reichie020212** [comment]
- Added page for importing beneficiary to CRVS with search criteria
- Added page for Data Source
- Updated the wizard for program creation to add a new dropdown field named "Data Source"
- Able to import beneficiaries.

**Comment by adriancris** [comment]
QA Passed
Working as expected

Test Cases executed:
TSOS-201 to TSOS-210

**Comment by adriancris** [comment]
Tested and approved but actions were needed

There was a bug found by dev and was fixed in another ticket - Fix number of recoards shown in the search - DCI
[#80](https://github.com/OpenSPP/openspp-api/issues/80)
