### ISSUE TITLE
API: (GET) Get the list of programs

### ISSUE THREAD

**Issue by gonzalesedwin1123** [OpenSPP/openspp-api#7]
Reference: API doc: https://docs.google.com/document/d/1jGVTC4WLons2elJ0RprPSRrN38d_LR84E3kRmnCX6iI/edit#heading=h.16sok7pft9is

Repository: https://github.com/OpenSPP/openspp-api

- [x] Added a new API for getting the list of programs

Output Fields:

- name
- company_id
- cycles_count
- active
- last_updated

API: /api/spp_api/1/Programs

**Comment by emjay0921** [comment]
Started working on this now.

**Comment by adriancris** [comment]
tested and approved without comments
