### ISSUE TITLE
Setting up Swagger documentation for the APIs

### ISSUE THREAD

**Issue by dasunhegoda** [OpenSPP/openspp-api#70]
This issue aims to set up Swagger documentation for our APIs, which have been developed for ACF.
Purpose

Purpose
- Swagger will enable both internal team members and external users to visualize the API structure and understand its functionalities without delving into the code.
- It will help in maintaining a standard format for our API documentation, ensuring consistency and ease of use.
- External developers can interact with the API directly from the documentation, making testing and debugging more efficient.

Expectations
- Each endpoint should be documented, including its purpose, request parameters, response structure, and error codes.

API spec: https://docs.google.com/document/d/1jGVTC4WLons2elJ0RprPSRrN38d_LR84E3kRmnCX6iI/edit?usp=sharing

This will be published in the docs.openspp.org

**Comment by adriancris** [comment]
QA Passed
Working as expected
Test cases executed:
TSOS-192
TSOS-195
TSOS-196
TSOS-197

**Comment by adriancris** [comment]
BUGS found:
1. Pagination not working (offset and limit)
2. last_modified_date field is required after a previous value is input

**Comment by adriancris** [comment]
Bugs found (above) are now fixed.
