### ISSUE TITLE
Adding Bearer token capability to the API

### ISSUE THREAD

**Issue by dasunhegoda** [OpenSPP/openspp-api#72]
- Try to use the Data Source (developed for the OpenCRVS integration) to manage the bearer token

**Comment by gonzalesedwin1123** [comment]
@adriancris, did this already passed QA?

**Comment by adriancris** [comment]
QA Passed
Working as expected
Test case executed:
TSOS-198, TSOS-112 to TSOS-128, TSOS-142, TSOS-145

**Comment by adriancris** [comment]
hi @gonzalesedwin1123 
yes has already passed QA
