### ISSUE TITLE
G2P Connect API Implementation - Server Implementation

### ISSUE THREAD

**Issue by dasunhegoda** [OpenSPP/openspp-api#76]
API spec: https://g2p-connect.github.io/specs/release/html/registry_core_api_v1.0.0.html
https://digital-convergence-initiative-d.gitbook.io/dci-standards-1/dci/readme

- Review the DCI API specification thoroughly to understand the requirements.
- Create the necessary API endpoints as outlined in the specification.
- Implement data processing and validation logic for incoming requests.
- Ensure proper error handling and response formatting.
- Test the API thoroughly to verify its functionality and compliance with the spec.
- Document the approach you took
- Conduct integration testing to ensure compatibility with other components.
- Seek peer review for code quality and best practices.
- Address any feedback or issues that arise during development

**Comment by reichie020212** [comment]
The getting of access token, authentication, and retrieving data API are now working

I didn't used the architecture in spp_api module but rather i used the route of core odoo and used werkzeug library for response

These are some of the reasons why I didn't used the architecture of spp_api
- SPP API is using Basic authentication
- SPP API have specific path and specific use for it
- in the G2P-connect spec, we need to use POST to retrieve data, in SPP_API, it uses GET
- the error message is also different from g2p-connect specs
- ApiV1Controller is too specific for Famoco

**Comment by adriancris** [comment]
hi @reichie020212 
for the Search Registry API, the displayed filter of the birthdates is incorrect.

My filter greater than 2010-11-02 but lesser than 2024-01-04.

But in the response, I can see birthdates before 2010.

Kindly check. Thank you.

![Image](https://github.com/OpenSPP/openspp-api/assets/138551361/5014a513-2e35-4e42-8dc3-24dbddaefb58)

**Comment by reichie020212** [comment]
> hi @reichie020212 for the Search Registry API, the displayed filter of the birthdates is incorrect.
> 
> My filter greater than 2010-11-02 but lesser than 2024-01-04.
> 
> But in the response, I can see birthdates before 2010.
> 
> Kindly check. Thank you.
> 
> ![Image](https://private-user-images.githubusercontent.com/138551361/294211205-5014a513-2e35-4e42-8dc3-24dbddaefb58.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0MTk3NTMsIm5iZiI6MTcwNDQxOTQ1MywicGF0aCI6Ii8xMzg1NTEzNjEvMjk0MjExMjA1LTUwMTRhNTEzLTJlMzUtNGU0Mi04ZGMzLTI0ZGJkZGFlZmI1OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwNVQwMTUwNTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNDk4MzQxZmNkZGViNmM1MmJhMzFjMGQ0MTQ1NTA2MTI2ZjI2YTQyNmRkNWM2MzBjNzg0MGNhYmQxMTdiOTExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.oyXN65ogQRENR9TFJaTebAi34dWWwZR7NXniK9wm9QE)

done fixing this issue and already pushed the code to the PR

**Comment by adriancris** [comment]
Bug fixed:




![Image](https://github.com/OpenSPP/openspp-api/assets/138551361/b3faf255-1098-4cc3-b103-d3282b3bdf11)




![Image](https://github.com/OpenSPP/openspp-api/assets/138551361/4dc77576-f06a-4992-8282-7d5beab955c8)

**Comment by adriancris** [comment]
QA Passed.
Working as expected.
Test cases executed:
TSOS-199 to TSOS-201
