### ISSUE TITLE
API: (GET) Get the list of cycles for a program

### ISSUE THREAD

**Issue by gonzalesedwin1123** [OpenSPP/openspp-api#8]
Reference: API doc: https://docs.google.com/document/d/1jGVTC4WLons2elJ0RprPSRrN38d_LR84E3kRmnCX6iI/edit#heading=h.93dvvace8g8i

Repository: https://github.com/OpenSPP/openspp-api

**How to Use:**

GET List of Cycles

Full Path: /api/spp+api/1/g2p.cycle/
Method: GET
Sample Payload
- {
    "request_id": "sjd12hc",
}
Sample Response
- {
    "results": [
        {
            "id": 25,
            "end_date": "2023-07-12",
            "name": "Cycletest35",
            "program_id": [
                2,
                "qwe1"
            ],
            "start_date": "2023-07-10",
            "state": "draft",
            "write_date": "2023-08-03 04:19:13"
        },
        {
            "id": 1,
            "end_date": "2023-08-31",
            "name": "Cycle 1",
            "program_id": [
                2,
                "qwe1"
            ],
            "start_date": "2023-08-01",
            "state": "approved",
            "write_date": "2023-07-06 07:00:02"
        },
        {
            "id": 3,
            "end_date": "2023-08-31",
            "name": "Cycle 1",
            "program_id": [
                1,
                "qwe"
            ],
            "start_date": "2023-08-01",
            "state": "draft",
            "write_date": "2023-07-31 09:16:35"
        },
    ],
    "total": 19,
    "offset": 0,
    "limit": 500,
    "version": 1,
    "time_stamp": "2023-08-07 05:01:29.708152",
    "reply_id": "a7b1d211-2970-4042-9f2e-e59ac9a5f041"
}

GET Details of specific Cycle

Full Path: /api/spp+api/1/g2p.cycle/<cycle_id:int>
Method: GET
Sample Payload
- {
    "request_id": "sjd12hc2",
}
Sample Response
- {
    "id": 2,
    "end_date": "2023-09-30",
    "name": "Cycle 2",
    "program_id": [
        2,
        "qwe1"
    ],
    "start_date": "2023-09-01",
    "state": "draft",
    "write_date": "2023-07-10 10:03:54",
    "time_stamp": "2023-08-07 05:15:16.478470",
    "reply_id": "9b88afd5-93d0-4195-883d-fffe65040197"
}

**Comment by adriancris** [comment]
QA Passed
Working as expected
![image](https://github.com/OpenSPP/openspp-api/assets/138551361/b83dcff2-8d65-40f7-a29b-d5cd4c1e13a6)

**Comment by adriancris** [comment]
hi @reichie020212, @gonzalesedwin1123 @dasunhegoda 

ACF Dev; Feb 6, 2024

Pagination in this API is not accurate.

Expected Result: A cycle in the current page should NOT repeat in the next page.

Actual Result: A cycle is repeated in the next page

https://drive.google.com/file/d/1Bt_1Y8gSVOKMRTPcnBm6LtEHGcztjMOB/view?usp=sharing
