### ISSUE TITLE
Fix number of recoards shown in the search - DCI

### ISSUE THREAD

**Issue by dasunhegoda** [OpenSPP/openspp-api#80]
![Image](https://github.com/OpenSPP/openspp-api/assets/2864612/bd41d850-42fa-4aeb-89ba-474890f1c0e1)

**Comment by adriancris** [comment]
QA Passed.
Working as expected.
(0) records is now hidden.


![Image](https://github.com/OpenSPP/openspp-api/assets/138551361/e5654bc4-7956-4548-9363-257f5fb86657)
