### ISSUE TITLE
Improve Swagger documentation

### ISSUE THREAD

**Issue by dasunhegoda** [OpenSPP/openspp-api#88]
This ticket focuses on updating the Swagger documentation
 
- Customize the Swagger UI to incorporate the OpenSPP theme, including color schemes, fonts, and layout styles.
- Verify theme consistency across all Swagger documentation pages.
- Cross-reference the current Swagger API endpoints with the latest API Spec document.
- Remove any endpoints from the Swagger documentation that are not present in the API Spec.
- Deploy the updated Swagger documentation to demo.openspp.org.
- Ensure that the documentation is accessible and correctly displays the updated information and theme.

**Comment by emjay0921** [comment]
Finalizing the "Customize the Swagger UI to incorporate the OpenSPP theme, including color schemes, fonts, and layout styles.".
