### ISSUE TITLE
Fix Area Import

### ISSUE THREAD

**Issue by dasunhegoda** [OpenSPP/openspp-api#89]
**Issue Description**

- The areas import functionality is currently not working as expected. It needs to be fixed to ensure proper data import.

- **Action Item**: Import a sample dataset using 'humdata' to test and validate the import process.

- **Naming Convention Issue**: The root name for imported areas should be 'Sri Lanka' instead of '- Sri Lanka'. This needs correction to maintain consistency and accuracy in data representation.

- **Structure Visualization**: There's an issue with how the structure is displayed post-import. It should be shown properly, reflecting the correct hierarchical of the data.

**Expected Outcome**

- Successful import of the dataset.
- Correct naming convention.
- Proper structural representation in the interface.

**Comment by gonzalesedwin1123** [comment]
@reichie020212 let me know if you already have a PR for this.

**Comment by adriancris** [comment]
@reichie020212 
I get an error when importing a dataset from Humdata without the Area (sq/km) column. 
This would be a bug if AREA_SQKM is not mandatory. 

Sample of data set and error encountered is attached.



[jpn_adm_gz_2019.xls](https://github.com/OpenSPP/openspp-api/files/14061164/jpn_adm_gz_2019.xls)



![Image](https://github.com/OpenSPP/openspp-api/assets/138551361/bc31075e-989c-494e-b2bf-f7c2ad0ee984)

**Comment by adriancris** [comment]
@reichie020212 
when updating an area with the same code, it creates another area instead.


![Image](https://github.com/OpenSPP/openspp-api/assets/138551361/14d387c2-ba1d-474b-8153-b8d9117a16d0)

**Comment by dasunhegoda** [comment]
@reichie020212 : Can you check the above?

**Comment by reichie020212** [comment]
@dasunhegoda it's already fixed in odoo 17. I'll close the ticket now. Thank you.
