### ISSUE TITLE
API: (GET) Get the list of service points

### ISSUE THREAD

**Issue by gonzalesedwin1123** [OpenSPP/openspp-api#9]
Reference: API doc: https://docs.google.com/document/d/1jGVTC4WLons2elJ0RprPSRrN38d_LR84E3kRmnCX6iI/edit#heading=h.462m58echgrg

Repository: https://github.com/OpenSPP/openspp-api

**Comment by adriancris** [comment]
hi @nhatnm0612 

kindly check this side-by-side comparison between the documentation and the actual result in postman for Get the list of service points 

https://drive.google.com/file/d/1KE6Ak4450t8Xwh4Etkr0-_S0PZUqTsn2/view?usp=drive_link

**Comment by adriancris** [comment]
Setting the status back to In Progress.
@nhatnm0612 to investigate res_partner_company_id in Postman versus the expected paramater in the documentation (company_id)
![image](https://github.com/OpenSPP/openspp-api/assets/138551361/99d72510-57e8-4099-9591-64bc4676c89f)

**Comment by nhatnm0612** [comment]
> Setting the status back to In Progress.
> @nhatnm0612 to investigate res_partner_company_id in Postman versus the expected paramater in the documentation (company_id)

@adriancris should be ok after re-deploying
